### ISSUE TITLE
Unable to change options settings

### ISSUE THREAD

**Issue by StealtHiBye** [ChuckTheSheep/SwapIt#3]
So, I started the game with only this mod enabled, went to options and tried to change blood decal from 70% to 100%, clicked in apply, and got an error message. Tried accept, and got another error message. Clicked exit, and when the game asked if I wanted to save the changes, clicked in yes and got an error, returning to the options menu. Clicked again in exit, then no, and the game returned to the main menu. I then exited. Not sure if it's something on my end, don't understand coding enough to judge that, but there it is. Error log should be below.
[console.txt](https://github.com/ChuckTheSheep/SwapIt/files/6644887/console.txt)

**Comment by Chuckleberry-Finn** [comment]
Thank you I'll be looking into this.

**Comment by Chuckleberry-Finn** [comment]
Can you please confirm if this issue has been fixed with the recent patch?

**Comment by StealtHiBye** [comment]
Yep, it's working fine now. Thank you for fixing it!

**Comment by Chuckleberry-Finn** [comment]
☺️
